// Service Worker generated by next-pwa with navigation fallback for offline support
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all assets generated by next-pwa
precacheAndRoute(self.__WB_MANIFEST);

cleanupOutdatedCaches();

// Cache Google Fonts
registerRoute(
  ({ url }) => url.origin.startsWith('https://fonts.googleapis.com') || url.origin.startsWith('https://fonts.gstatic.com'),
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [new ExpirationPlugin({ maxEntries: 4, maxAgeSeconds: 365 * 24 * 60 * 60 })],
  })
);

// Cache images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 })],
  })
);

// Network first for API calls to local backend
registerRoute(
  ({ url }) => url.pathname.startsWith('/api') && url.origin.includes('localhost:8000'),
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 10,
    plugins: [new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 24 * 60 * 60 })],
  })
);

// Navigation fallback – serve the offline page when navigation fails
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'pages',
    plugins: [{
      handlerDidError: async () => {
        // Return the offline HTML page from cache
        return caches.match('/offline');
      },
    }],
  })
);

self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});
