/* eslint-disable no-undef */
// Service Worker generated by next-pwa with navigation fallback for offline support
import { precacheAndRoute, cleanupOutdatedCaches, matchPrecache } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, NetworkOnly } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// Precache all assets generated by next-pwa
precacheAndRoute(self.__WB_MANIFEST);

cleanupOutdatedCaches();

// Navigation fallback – serve the offline page when navigation fails or backend is down
registerRoute(
  ({ request }) => request.mode === 'navigate',
  async ({ request, event }) => {
    try {
      const response = await fetch(request);
      // If valid response, clone and cache
      if (response.ok) {
        const responseClone = response.clone();
        const cachePromise = caches.open('pages').then((cache) => {
          return cache.put(request, responseClone);
        });
        if (event && event.waitUntil) {
          event.waitUntil(cachePromise);
        }
        return response;
      }
      throw new Error('Server error or 404');
    } catch (err) {
      // Network failed or server error -> try cache
      
      // 1. Try Runtime Cache (pages visited before)
      const cachedResponse = await caches.match(request);
      if (cachedResponse) return cachedResponse;
      
      // 2. Try Precache (static pages generated at build time)
      const precachedResponse = await matchPrecache(request);
      if (precachedResponse) return precachedResponse;
      
      // 3. Fallback to offline page
      return caches.match('/offline');
    }
  }
);

// Cache Google Fonts
registerRoute(
  ({ url }) => url.origin.startsWith('https://fonts.googleapis.com') || url.origin.startsWith('https://fonts.gstatic.com'),
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [new ExpirationPlugin({ maxEntries: 4, maxAgeSeconds: 365 * 24 * 60 * 60 })],
  })
);

// Cache images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 })],
  })
);

// Cache manifest.json and PWA icons
registerRoute(
  ({ url }) => 
    url.pathname === '/manifest.json' ||
    url.pathname.startsWith('/android-chrome-') ||
    url.pathname.startsWith('/apple-touch-') ||
    url.pathname === '/favicon.ico',
  new CacheFirst({
    cacheName: 'pwa-assets',
    plugins: [new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 30 * 24 * 60 * 60 })],
  })
);

// Background Sync for API Mutations (POST, PUT, DELETE, PATCH)
const bgSyncPlugin = new BackgroundSyncPlugin('offline-mutations', {
  maxRetentionTime: 24 * 60, // Retry for max of 24 Hours (specified in minutes)
});

registerRoute(
  ({ url, request }) => 
    url.pathname.startsWith('/api') && 
    url.origin.includes('localhost:8000') &&
    ['POST', 'PUT', 'DELETE', 'PATCH'].includes(request.method),
  new NetworkOnly({
    plugins: [bgSyncPlugin]
  })
);

// Network first for API GET calls to local backend
registerRoute(
  ({ url, request }) => 
    url.pathname.startsWith('/api') && 
    url.origin.includes('localhost:8000') &&
    request.method === 'GET',
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 10,
    plugins: [new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 24 * 60 * 60 })],
  })
);

self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});
